### ISSUE TITLE
Does not work in PHP version 7.2

### ISSUE THREAD

**Issue by admln** [kraken-ng/Kraken#4]
![image](https://user-images.githubusercontent.com/6093870/228828044-9b87697c-9541-457a-b646-83096321e4cd.png)

![image](https://user-images.githubusercontent.com/6093870/228828214-81fd2c0d-39f2-4cd3-89f6-002c498c0a08.png)

**Comment by secu77** [comment]
Hello! It seems that the error that occurs in the agent is caused by the `posix_getuid()` function (it seems that it is because it is not installed). In principle, it is not a PHP version problem, because the `posix_getuid()` function is in the core since version 4. 

![image](https://user-images.githubusercontent.com/23587075/229223165-067cfd11-ea1c-4034-8b91-a177b4532df1.png)

It seems that, in your environment, this extension is not installed. Can you give me more information about the environment where you are deploying the PHP agent (**operating system and version, PHP extensions installed, and PHP 7.2 packages installed**). With this information I will proceed to recreate it and see why it fails.

P.D: Based on [this link](https://stackoverflow.com/questions/2197366/how-to-install-posix-in-php), you may need to install the following package: `yum install php-process`
